// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link': string;
  'login': string;
  'login__form': string;
  'submit': string;
}
export const cssExports: CssExports;
export default cssExports;
