// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formWrapper': string;
  'formWrapper__form': string;
  'link': string;
}
export const cssExports: CssExports;
export default cssExports;
