// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spinner': string;
  'spinner1': string;
  'spinner2': string;
  'spinner3': string;
}
export const cssExports: CssExports;
export default cssExports;
