// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'errorWrap': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
